-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 17, 2017 at 11:11 PM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `ambot`
--

-- --------------------------------------------------------

--
-- Table structure for table `college`
--

CREATE TABLE IF NOT EXISTS `college` (
  `inten` varchar(100) NOT NULL,
  `f1` varchar(1000) NOT NULL,
  `f2` varchar(1000) NOT NULL,
  `f3` varchar(1000) NOT NULL,
  `f4` varchar(1000) NOT NULL,
  `f5` varchar(1000) NOT NULL,
  `f6` varchar(1000) NOT NULL,
  `f7` varchar(1000) NOT NULL,
  `f8` varchar(1000) NOT NULL,
  `f9` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `college`
--

INSERT INTO `college` (`inten`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`) VALUES
('about', 'Amal Jyothi College of Engineering has established itself as a benchmark of excellence in technical higher education and research. Founded in 2001 by the Catholic Diocese of Kanjirappally, Amal Jyothi is approved by the AICTE and affiliated to APJ Abdul Kalam Technological University (KTU), Kerala. It is the first new generation engineering college in Kerala with the prestigious NBA accredited departments and the first engineering college in Kerala with the recognition of ‘A’ grade from NAAC.', 'Tel: + 91 4828 305500 / 305555Fax: + 91 4828 251136website: www.ajce.inE-mail IDsinfo@amaljyothi.ac.inadmissions@amaljyothi.ac.in', '65 acres of campus, 16.5 lakh sq.ft. built-up area', 'Amal Jyothi College of EngineeringKanjirappally,Koovappally P.O.Kottayam Dt.,KeralaIndia.PIN – 686518', 'AJCE is the first new generation engineering college in Kerala with the prestigious NBA accredited departments and the first engineering college in Kerala with the recognition of ‘A’ grade from NAAC.', 'Patron:\r\nHis Excellency Mar Mathew Arackal, Bishop of Kanjirapally\r\n\r\nManager:\r\nRev. Fr. Dr. Mathew Paikatt\r\n\r\nDirector:\r\nRev. Dr. P.T. Joseph, S.J\r\n\r\nPrincipal:\r\nDr. Z V Lakaparampil\r\n\r\nBursar:\r\nRev.  Fr. Dominic Karikkattil', '', '', ''),
('auto', 'Prof K Vijayan, M TechProfessor & HOD, Dept. of Automobile Engineering', 'Contact – Ph. No.: + 91 4828 305623\r\nEmail ID: kvijayan@amaljyothi.ac.in', 'Prof K Vijayan\r\nHead, Dept. of Automobile  Engineering Amal Jyothi College of Engineering, Kanjirappally', 'Area of specilization: Automobile Engineering', 'Number of faculties: 23', 'Retired as Deputy Director, Centre for Technology Development and Transfer (CTDT) at Anna University', 'Department Location: Divisional Block C (Automobile Block)', 'Placemnt Automobile:\r\nGeneral motors, Volkswagon, Mahindra&Mahindra, Tata motors, Bajaj auto etc..', 'B tech seats:-60'),
('bursar', 'Rev.  Fr. Dominic Karikkattil\r\nbursar of AJCE', 'Ph: 04828 305501\r\nMob:  9961377070\r\nEmail: bursar@amaljyothi.ac.in', 'Manager, Amal Jyothi College of Engineering\r\nKanjirappally, Koovappally P.O.\r\nKottayam Dt., Kerala\r\nIndia. PIN – 686518', '', '', '', '', '', ''),
('chemical', 'Prof.V.K.Sasikumar, M TechProfessor & HOD, Dept. of Chemical Engineering', 'Mob: + 91 9946664027\r\nEmail ID: vksasikumar@amaljyothi.ac.in', 'Prof.V.K.Sasikumar \r\nHead, Dept. of Chemical Engineering\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of Specialization: Chemical Reaction Engineering, Environmental Engineering, Energy Engineering', 'Number of faculties: 16', 'Dean& HOD : Sree Buddha College of Engineering,Pattoor, Alappuzha Dist. from 2.2.2014 to 16/12/2015\r\nProfessor : METS School of Engg,Mala in the Dept of Biotechnology Engg from 1.6.2010 to Dec, 2014\r\nProfessor and HOD: Sahrdaya College Of Engg,Kodakara in the Department   of Biotechnology Engg(from2.2.2009 to 3.04.2010)', 'Department Location: Division Block C (Automobile Block)', 'Placement Chemical: ONGC, BPCL, IOCL, NPCIL, NTPC, Pollution control boards, Fertilizer plants etc..', 'B Tech seats:-60\r\nM Tech: Nano Technology:-24'),
('civil ', 'Sr.Claramma Rosary, M Tech\r\nProfessor & HOD, Dept. of Civil engineering', 'Ph. No.: + 91 4828 234036, 234225\r\nEmail ID:clarammarosary@amaljyothi.ac.in', 'Sr.Claramma Rosary\r\nHead, Dept. of Civil Engineering\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of specilization: Environmental Engineering', 'Number of faculties : 40', 'Lecturer in civil engineering, Carmel Polytechnic college Alappuzha,(1982-2000)\r\nHead of department of Civil Engineering, Carmel Polytechnic college Alappuzha, (2000-2007)', 'Department Location :  Central Complex', 'Placement Civil:Irrigation dept, CPWD, GALFAR, L&T etc..', 'B Tech seats:-120M Tech : structural engg & construction manamement:-24computer aided structural engineering:-24'),
('courses', 'B.Tech : 9 branches.\r\ntotal seats: 780', 'M.Tech : 8 streams\r\ntotal seats: 180', 'MCA : 3 streams\r\ntotal seats : 180', 'Add on courses:GATA Coaching , Foreign language courses , CAD Training , Driving academy , CNC vertical machining centre , Heavy duty automobile technology', 'B Tech courses:-Automobile engineering,chemical engineering,civil engineering,computer science & engineering,Electronics&communication engineering,Electrical&electronics engineering,Information Technology,Metallurgy,Mechanical engineering', 'M Tech courses:-Nano Technology,structural engineering and management,computer aided structural engineering,computer science & engineering,communication Engineering,power electronics and power systems,Energy systems,machine design', 'MCA Regular\r\nMCA Lateral Entry\r\nDual Degree MCA', 'special courses only in AJCE:\r\nDDMCA\r\nMetallurgy\r\nEICHER automobile diploma course', 'DEPARTMENTS(total 9 depts):-\r\nAutomobile engineering,\r\nChemical engineering,\r\nCivil engineering,\r\nComputer science & engineering,\r\nElectronics&communication engineering,\r\nElectrical&electronics engineering,\r\nInformation Technology,\r\nMetallurgy,\r\nMechanical engineering'),
('cs', 'Mr Manoj T Joy, M Tech, Phd*Professor & HOD, Dept. of Computer Science and Engineering', 'Mob: + 91 9447661414\r\nTel: + 91 4828 305544 (O)\r\nEmail ID: \r\nhodcse@amaljyothi.ac.in \r\nmanojtjoy@amaljyothi.ac.in', 'Prof. Manoj T Joy\r\nHead, Dept. of Computer Science and EngineeringAmal Jyothi College of Engineering, Kanjirappally', 'Area of specilization: Network Communication', 'Number of faculties: 34', 'Worked in the Department of Computer Science, College of Engineering ChenganoorWorked in the Department of Computer Science, College of Engineering Kalloopara', 'Department Location:   Ground Floor, Divisional Block A', 'Placement cs:\r\nTCS, IBM, SunTech, Accenture, UST Global, IBS Software, HCL Technologies etc..', 'B Tech seats:-120M Tech :computer Science & engg:-24'),
('dean', 'Prof. V.I. Cherian, ME\r\nDean, Academic\r\nArea of Specialization: Load Flow studies', 'Dr. James Jacob, Phd\r\nDean, Research\r\nArea of Specialization: CAD for VLSI', 'Prof. Tomy Joseph\r\nDean, Administration\r\nArea of Specialization: Mechanical Engineering', '', '', '', '', '', ''),
('director', 'Rev. Dr. P.T. Joseph, S.J, M.Sc, M.Th, MBA,Phd', 'He is a leading light in technical higher education', '', '', '', 'Independent Director of Ortel communications, Bhubaneswar,  from 2010  till date\r\nDirector: Marian International Institute of Management, Kuttikanam, 2014 onwards\r\nDirector, Xavier Institute of Management, Bhubaneswar, Orissa 2007-2012\r\nResearch Fellow and Faculty :Lal Bahadur Shastri National Academy of Administration, Mussorie 2013-2014\r\nDirector, Pastoral Management Program, JDV Pune, 2012-2013\r\nProfessor, XLRI, Jamshedpur, 1996-2007', '', '', ''),
('ec', 'Prof K G SatheeshkumarProfessor & HOD, Dept. of Electronics and Communication Engineering', 'Contact : Ph. No.+ 91 4828 305532, + 91 4828 305525, 251409\r\nEmail ID	hodece@amaljyothi.ac.in', 'Prof K G Satheeshkumar\r\nDept. of Electronics and Communication Engineering Amal Jyothi College of Engineering, Kanjirappally', 'Area of Specialization: Network Communication', 'Number of faculties: 43 ', '23rd August 1985 to 28th February 2001 in Indian Air Force .\r\n5th March 2001 to 5th Septemebr in VKNM VHSE Pathanmthitta, Kerala', 'Department Location: Divisional Block B', 'Placement ece:\r\nITI, BSNL, Civil aviation dept, ISRO, VLSI Design Industry, Tech Mahindra etc..', 'B Tech seats:- 120\r\nM Tech : communication engg:-24'),
('eee', 'Dr. P. C. Thomas\r\nProfessor & HoD, Department of Electrical and Electronics Engineering', 'Ph. No.: + 91 4828 305531, + 91 9495010565\r\nEmail ID: pcthomas@amaljyothi.ac.in', 'Dr. P. C. Thomas\r\nHead, Dept. of Electrical and Electronics Engineering\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of Specialization: Power system realibility, Stochastic processes', 'Number of faculties: 34\r\n', '2001-2004 (4’) Madanapalle Institute of Technology and Science, HOD-EEE, Madanapalle, Andhra Pradesh\r\n2000 (1’) Elsoft Technologies, Bangalore Component Engr.', 'Department Location: Divisional Block B', 'Placement eee: ISRO, DMRC, KSEB, BSNL, samsung, TCS etc..', 'B Tech seats: 60\r\nM Tech seats : power Electronics&power systems:-18\r\nEnergy Systems:- 24'),
('fee', 'BTech Fee Structure\r\nFor ME & CH =>\r\nTuition Fee(Per Year):Rs. 75,000/- \r\nInterest free refundable deposit: Rs. 1,00,000/- \r\nCaution deposit: Rs. 10,000/- \r\nPTA, Training and Other Fee (Yearly): Rs. 10,000/- \r\nUniversity fee (Yearly) and exam fee: Rs. 2,700/- ** \r\nAdmission fee: Rs. 500/- \r\nTotal: Rs. 1,98,200/- \r\n\r\nFor AU, CE, CSE, ECE, EEE, IT & MT =>\r\nTuition Fee(Per Sem):Rs. 37,500/- \r\nInterest free refundable deposit: Nil \r\nCaution deposit: Rs. 10,000/- \r\nPTA, Training and Other Fee (Yearly): Rs. 10,000/- \r\nUniversity fee (Yearly) and exam fee: Rs. 2,700/- ** \r\nAdmission fee: Rs. 500/- \r\nTotal: Rs. 60,700/- \r\n\r\n* May vary as per Kerala Govt norms.   \r\n** May vary as per KTU norms.', 'MTech Fee Structure =>\r\n\r\nTuition fee (semester wise): 40,000\r\nSpecial Fee (semester wise): 10,000\r\nAdmission Fee: 500\r\nKTU Student Administration Fee: 1,000\r\nCaution Fee Deposit: 5,000\r\nStudent welfare fund: 2,620\r\nSeminars,conference,internet etc.: 2,650\r\nPTA: 5,00\r\nTotal: 62,270', 'MCA Fee Structure \r\n\r\nFor  Reg, LE & Int 4 & 5 =>\r\nAdmission Fee (One Time): Rs. 500/- \r\nSpecial Fee (Yearly): Rs. 1,200/- \r\nAdministration Fee (One Time): Rs. 1,000/- \r\nTuition Fee (Per Semester) (Govt order): Rs. 25,000/- \r\nCaution Fee Deposit (One Time – Refundable): Rs. 10,000/- \r\nStudent welfare fund (Yearly): Rs. 2,445/- \r\nSeminars, conference, internet etc (Yearly): Rs. 2,600/- \r\nPTA (Yearly): Rs. 500/- \r\nTotal: Rs. 43,245/-\r\n\r\nFor INT- First 3 Years =>\r\nAdmission Fee (One Time): Rs. 500/- \r\nSpecial Fee (Yearly): Rs. 1,200/- \r\nAdministration Fee (One Time): Rs. 1,000/- \r\nTuition Fee (Per Semester) (Govt order): Rs. 18,750/- \r\nCaution Fee Deposit (One Time – Refundable): Rs. 10,000/- \r\nStudent welfare fund (Yearly): Rs. 2,445/- \r\nSeminars, conference, internet etc (Yearly): Rs. 2,600/- \r\nPTA (Yearly): Rs. 500/- \r\nTotal: Rs. 36995/-', 'Hostel Fees for boys.\r\n\r\nB Tech: Rs. 36700/-\r\nM Tech: Rs. 41400/-\r\nMCA: Rs. 34400/-', 'Hostel Fees for girls.\r\n\r\nB Tech: Rs. 36800/-\r\nM Tech: Rs. 41500/-\r\nMCA: Rs. 37000/-', '', '', '', ''),
('fest', 'Azure', 'AZURE is a techno-cultural fest conducted every year.', 'Arena', 'ARENA a four-day inter-engineering college Basketball tournament is held in the college stadium every year since 2007.', 'Aspire', 'ASPIRE: All Kerala Inter-Engineering College Volleyball Tournament held in AJCE.', '', '', ''),
('hostel', 'Hostel Admission day arrangementsFee Payment online only.Student & parent / guardian should sign the affidavit & application in front of Hostel in-charge.Vehicle Parking arrangements & Hostel Entry:Boys should park their vehicles inside college campus and enter through “block C” bridge to Boys hostel.Girls should park their vehicles near ladies hostel, laundry and should enter via ladies hostel front portico.', '', '', 'Hostel Reception:\r\n+91 4828 305200 (Santhom)\r\n+91 9061344466\r\n+91 9061344477\r\n+91 4828 301300 (Amala)\r\n+91 4828 305599\r\n+91 9961247737\r\nhostels@amaljyothi.ac.in\r\nwww.amaljyothi.ac.in', 'POSTAL ADDRESSSanthom / Amala Hostel\r\nAmal Jyothi College of Engineering\r\nKoovappally P.O., \r\nKanjirappally\r\nKottayam Dt., \r\nKerala, \r\nS. India - 686518', '', '', '', ''),
('it', 'Prof Sandhya Ramakrishnan,Professor & HOD, Dept. of Information Technology', 'Contact – Ph. No.: +91 4828305609, +91 9744136945, +91 9446600936\r\nEmail ID: hodit@amaljyothi.ac.in', 'Prof Sandhya Ramakrishnan \r\nHead, Dept. of Information Technology\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of Specialization: Big Data Analytics', 'Number of faculties: 21\r\n', 'Guest Lecturer at Cochin University of Science & Engineering, Govt. Polytechnic, Purapuzha, Kochi from March 2001 to August 2001', 'Department Location: Ground Floor, Divisional Block- A [ Left Wing ]', 'Placement it:\r\nTCS, UST Global, CTS, HCL Tech, IBM, Accenture etc..', 'B Tech seats:- 60'),
('location', 'Amal Jyothi College of EngineeringKanjirappally, Koovappally P.O.Kottayam Dt., KeralaIndia. PIN – 686518', 'Koovappally, 7km from Kanjirapally towards Erumely. 250m before reaching koovapally.', '', '', '', '', '', '', ''),
('manager', 'Rev. Fr. Dr. Mathew Paikatt,\r\nManager of AJCE', 'Ph: 04828 305501\r\nMob: 9544494704\r\nEmail: manager@amaljyothi.ac.in', 'Manager, Amal Jyothi College of Engineering\r\nKanjirappally, Koovappally P.O.\r\nKottayam Dt., Kerala\r\nIndia. PIN – 686518', '', 'Former Manager: Rev. Fr. Varghese Parinthirickal\r\nEmail: manager@amaljyothi.ac.in,\r\nMble: +91 9446222377', '', '', '', ''),
('mca', 'Rev. Fr. Rubin Thottupuram MCA, M Tech, PhD*Professor & HOD, Dept. of Computer Applications', 'Contact – Ph. No.: + 91 9447290939, + 91 4828 305635\r\nEmail ID: rubinthottupuram@amaljyothi.ac.in', 'Rev. Fr. Rubin Thottupuram \r\nHead, Dept. of Computer Applications\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of specialization: Semantic Web and Ontology Engineering', 'Number of faculties: 26\r\n', 'Guest Lecturer at Cochin University of Science & Engineering, Govt. Polytechnic, Purapuzha, Kochi from March 2001 to August 2001\r\nLecturer at Marian College Kuttikkanam, Dept. of MCA & BCA (2003 – 2005)', 'Faculty & HoD Room Location: Fourth Floor, Research Square', 'Placement mca:\r\nTCS, UST Global, HCL Technologies, Infosys, IBS software etc..', 'MCA Regular seats:- 60\r\nMCA Lateral Entry:-60\r\nDDMCA:-60'),
('mech', 'Prof K Sreekumar\r\nProfessor & HoD, Dept of Mechanical Engg', 'Ph. No.+ 91 4828 , + 91 94967 19817\r\nEmail ID: hodme@amaljyothi.ac.in', 'Prof K Sreekumar\r\nHead, Dept. of Mechanical Engineering\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of Specialization: Metallurgy', 'Number of faculties: 45\r\n', 'Sept 1975 – Dec 1979 – SENIOR SCIENTIFIC ASSISTANT – COMBAT VEHICLES R&D ESTABLISHMENT, (DRDO), AVADI.\r\nJan 1980-Sept 2011 – MATERIALS AND METALLURGY GROUP, ( MMG ) OF VIKRAM SARABHAI SPACE CENTER, ( ISRO), Trivandrum in various capacities. Retired on superannuation in September 2011 as Group Director – MMG (Engineer “G”).', 'Department Location: Central Complex', 'Placement mech:\r\nMajor industries including automobiles , space research, aeronautical, energy and utilities, air conditioning etc.', 'B Tech seats:-120\r\nM Tech: Machine Design:-18'),
('metallurgy', 'Dr K G Samuel, M.Tech, Ph D,\r\nProfessor & HOD, Dept. of Metallurgy', 'Contact – Ph. No.: + 91 4828 305624, + 91 98957 36781\r\nEmail ID: hodmt@amaljyothi.ac.in', 'Dr K G Samuel \r\nHead, Dept. of Metallurgy\r\nAmal Jyothi College of Engineering, Kanjirappally', 'Area of specilization: Mechanical Metallurgy', 'Number of faculties: 14\r\n', 'Bhabha Atomc Research Centre, Trombay 1968-1974\r\nIndira Gandhi Centre for Atomic Research, Kalpakkam 1974-2007', 'Department Location: Divisional Block C – (Automobile Block)', 'Placement metallurgy:\r\nTATA Steel, SAIL, DAE, NPCIL, ISRO, BSNL, ONGC, DMRC, HEC, BHEL etc..', 'B Tech seats:-60'),
('principal', 'Principal: Dr. Z V Lakaparampil, DIISc,Phd', 'Mob: + 91 9447162763\r\nTel: + 91 4828 305503 (O)\r\nlakaparampil@amaljyothi.ac.in\r\nprincipal@amaljyothi.ac.in', 'Principal, Amal Jyothi College of EngineeringKanjirappally, Koovappally P.O.Kottayam Dt., KeralaIndia. PIN – 686518', 'Area of Specialization: Embedded Controllers for Power Electronics', 'Former Principal: Rev. Dr. Jose Kannampuzha, M Tech, PhdPeriod: 2005-17Area of Specialization: Mechanical Engineering, Farm Machinery & Power', 'Senior Director, CDAC, Thiruvananthapuram A Scientific Society under DeitY, Government of IndiaDirector,  ER&DCI Institute of Technology, Educational Institute affiliated to Kerala Technological University (2006-2016)', '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `college`
--
ALTER TABLE `college`
 ADD PRIMARY KEY (`inten`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
